services:

  backend:
    build:
      context: ./backend
    container_name: magic-backend
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
    container_name: magic-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend